version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@vue/cli-plugin-babel"
      - dependency-name: "@vue/cli-plugin-eslint"
      - dependency-name: "@vue/cli-service"
      - dependency-name: "babel-eslint"
      - dependency-name: "core-js"
      - dependency-name: "eslint"
      - dependency-name: "eslint-plugin-vue"
      - dependency-name: "vue"
      - dependency-name: "vue-template-compiler"
