name: Ask a Question
description: Ask a question about a project.
title: "[Question]: "
labels: [Question]
body:
  # step 1
  - type: textarea
    id: question
    attributes:
      label: What is your question?
      description: Please describe the issue you are experiencing.
    validations:
      required: true
