name: Suggest an idea
description: Suggest an idea for this project.
title: "[Suggestion]: "
labels: [Suggestion, Contribution]
assignees:
body:
  # step 1
  - type: checkboxes
    id: checking
    attributes:
      label: "Please confirm the following before submitting a new suggestion:"
      options:
        - label: I looked for a similar idea [in the discussions](https://github.com/andrejsharapov/vue-box-shadows/discussions/5) and did not find it.
          required: true
        - label: I have [searched all issues](https://github.com/andrejsharapov/vue-box-shadows/issues?q=is%3Aissue) to make sure a similar issue doesn't exist.
          required: true
  # step 2
  - type: textarea
    id: message
    attributes:
      label: Tell us about your suggestion.
      description: Add any context or screenshots about the feature request here.
    validations:
      required: true
