export const baseShadow = {
  id: "-1",
  offsetX: "0",
  offsetY: "0.625rem",
  blur: "2.5rem",
  spread: "0",
  color: "0 0 0",
  opacity: 10,
  inset: false,
};

export const listShadows = [
  {
    id: "0",
    offsetX: 0,
    offsetY: 0,
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 0,
    inset: false,
  },
  {
    id: "1",
    offsetX: 0,
    offsetY: 0,
    blur: "1.25rem",
    spread: 0,
    color: "0 0 0",
    opacity: 10,
    inset: false,
  },
  {
    id: "2",
    offsetX: 0,
    offsetY: "1.25rem",
    blur: "3.75rem",
    spread: "-0.625rem",
    color: "0 0 0",
    opacity: 10,
    inset: false,
  },
  {
    id: "3",
    offsetX: 0,
    offsetY: "0.375rem",
    blur: "0.5rem",
    spread: "0",
    color: "0 0 0",
    opacity: 10,
    inset: false,
  },
  {
    id: "4",
    offsetX: 0,
    offsetY: "0.375rem",
    blur: "1.25rem",
    spread: 0,
    color: "0 0 0",
    opacity: 10,
    inset: false,
  },
  {
    id: "5",
    offsetX: "0",
    offsetY: "0.25rem",
    blur: "0.75",
    spread: "0.125",
    color: "0 0 0",
    opacity: 12,
    inset: false,
  },
  {
    id: "6",
    offsetX: 0,
    offsetY: 0,
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 0,
    inset: false,
  },
  {
    id: "7",
    offsetX: 0,
    offsetY: 0,
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 0,
    inset: false,
  },
  {
    id: "8",
    offsetX: 0,
    offsetY: "1rem",
    blur: "2.75rem",
    spread: "-0.75",
    color: "0 0 0",
    opacity: 25,
    inset: false,
  },
  {
    id: "9",
    offsetX: "0.125rem",
    offsetY: "0.125rem",
    blur: "0.125rem",
    spread: 0,
    color: "0 0 0",
    opacity: 6,
    inset: false,
  },
  {
    id: "10",
    offsetX: 0,
    offsetY: "0.125rem",
    blur: "0.375rem",
    spread: 0,
    color: "0 0 0",
    opacity: 40,
    inset: false,
  },
  {
    id: "11",
    offsetX: 0,
    offsetY: "0.375rem",
    blur: "1rem",
    spread: 0,
    color: "0 0 0",
    opacity: 0,
    inset: false,
  },
  {
    id: "12",
    offsetX: 0,
    offsetY: 0,
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 0,
    inset: false,
  },
  {
    id: "13",
    offsetX: 0,
    offsetY: "-1rem",
    blur: "0.375rem",
    spread: "-0.75rem",
    color: "0 0 0",
    opacity: 20,
    inset: false,
  },
  {
    id: "14",
    offsetX: 0,
    offsetY: "-0.375rem",
    blur: "0.5rem",
    spread: 0,
    color: "0 0 0",
    opacity: 10,
    inset: false,
  },
  {
    id: "15",
    offsetX: 0,
    offsetY: "-1.25rem",
    blur: "3.75rem",
    spread: "-0.75rem",
    color: "0 0 0",
    opacity: 10,
    inset: false,
  },
  {
    id: "16",
    offsetX: 0,
    offsetY: "-50px",
    blur: "100px",
    spread: "-30px",
    color: "0 0 0",
    opacity: 25,
    inset: false,
  },
  {
    id: "17",
    offsetX: 0,
    offsetY: "-16px",
    blur: "24px",
    spread: 0,
    color: "0 0 0",
    opacity: 20,
    inset: false,
  },
  {
    id: "18",
    offsetX: 0,
    offsetY: 0,
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 0,
    inset: false,
  },
  {
    id: "",
    offsetX: 0,
    offsetY: 0,
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 0,
    inset: false,
  },
  {
    id: "19",
    offsetX: 0,
    offsetY: 0,
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 0,
    inset: false,
  },
  {
    id: "20",
    offsetX: 0,
    offsetY: "-32px",
    blur: "40px",
    spread: 0,
    color: "0 0 0",
    opacity: 20,
    inset: false,
  },
  {
    id: "21",
    offsetX: "6px",
    offsetY: "6px",
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 5,
    inset: false,
  },
  {
    id: "22",
    offsetX: "-6px",
    offsetY: "6px",
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 5,
    inset: false,
  },
  {
    id: "23",
    offsetX: "6px",
    offsetY: "-6px",
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 0,
    inset: false,
  },
  {
    id: "24",
    offsetX: "-6px",
    offsetY: "-6px",
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 0,
    inset: false,
  },
  {
    id: "25",
    offsetX: "2px",
    offsetY: "2px",
    blur: "4px",
    spread: 0,
    color: "0 0 0",
    opacity: 20,
    inset: false,
  },
  {
    id: "26",
    offsetX: "-2px",
    offsetY: "2px",
    blur: "4px",
    spread: 0,
    color: "0 0 0",
    opacity: 20,
    inset: false,
  },
  {
    id: "27",
    offsetX: "2px",
    offsetY: "-2px",
    blur: "4px",
    spread: 0,
    color: "0 0 0",
    opacity: 20,
    inset: false,
  },
  {
    id: "28",
    offsetX: "-2px",
    offsetY: "-2px",
    blur: "4px",
    spread: 0,
    color: "0 0 0",
    opacity: 20,
    inset: false,
  },
  {
    id: "29",
    offsetX: "2px",
    offsetY: "4px",
    blur: "6px",
    spread: 0,
    color: "0 0 0",
    opacity: 14,
    inset: false,
  },
  {
    id: "30",
    offsetX: "-2px",
    offsetY: "4px",
    blur: "6px",
    spread: 0,
    color: "0 0 0",
    opacity: 14,
    inset: false,
  },
  {
    id: "31",
    offsetX: "2px",
    offsetY: "-4px",
    blur: "6px",
    spread: 0,
    color: "0 0 0",
    opacity: 14,
    inset: false,
  },
  {
    id: "32",
    offsetX: "-2px",
    offsetY: "-4px",
    blur: "6px",
    spread: 0,
    color: "0 0 0",
    opacity: 14,
    inset: false,
  },
  {
    id: "33",
    offsetX: "16px",
    offsetY: "16px",
    blur: "4px",
    spread: "-4px",
    color: "0 0 0",
    opacity: 20,
    inset: false,
  },
  {
    id: "34",
    offsetX: "-16px",
    offsetY: "16px",
    blur: "4px",
    spread: "-4px",
    color: "0 0 0",
    opacity: 20,
    inset: false,
  },
  {
    id: "35",
    offsetX: "16px",
    offsetY: "-16px",
    blur: "4px",
    spread: "-4px",
    color: "0 0 0",
    opacity: 20,
    inset: false,
  },
  {
    id: "36",
    offsetX: "-16px",
    offsetY: "-16px",
    blur: "4px",
    spread: "-4px",
    color: "0 0 0",
    opacity: 20,
    inset: false,
  },
  {
    id: "37",
    offsetX: 0,
    offsetY: 0,
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 0,
    inset: false,
  },
  {
    id: "38",
    offsetX: 0,
    offsetY: 0,
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 0,
    inset: false,
  },
  {
    id: "39",
    offsetX: 0,
    offsetY: 0,
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 0,
    inset: false,
  },
  {
    id: "40",
    offsetX: 0,
    offsetY: 0,
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 0,
    inset: false,
  },
  {
    id: "41",
    offsetX: 0,
    offsetY: 0,
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 0,
    inset: false,
  },
  {
    id: "42",
    offsetX: 0,
    offsetY: 0,
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 0,
    inset: false,
  },
  {
    id: "43",
    offsetX: 0,
    offsetY: "16px",
    blur: "4px",
    spread: "-12px",
    color: "0 0 0",
    opacity: 20,
    inset: false,
  },
  {
    id: "44",
    offsetX: 0,
    offsetY: "48px",
    blur: "96px",
    spread: "-32px",
    color: "0 0 0",
    opacity: 25,
    inset: false,
  },
  {
    id: "45",
    offsetX: 0,
    offsetY: "8px",
    blur: "16px",
    spread: 0,
    color: "0 0 0",
    opacity: 5,
    inset: false,
  },
  {
    id: "46",
    offsetX: 0,
    offsetY: "6px",
    blur: "8px",
    spread: 0,
    color: "0 0 0",
    opacity: 1,
    inset: false,
  },
  {
    id: "47",
    offsetX: 0,
    offsetY: "16px",
    blur: "24px",
    spread: 0,
    color: "0 0 0",
    opacity: 0,
    inset: false,
  },
  {
    id: "48",
    offsetX: 0,
    offsetY: 0,
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 0,
    inset: false,
  },
  {
    id: "49",
    offsetX: 0,
    offsetY: "32px",
    blur: "40px",
    spread: 0,
    color: "0 0 0",
    opacity: 20,
    inset: false,
  },
  {
    id: "50",
    offsetX: 0,
    offsetY: 0,
    blur: "68px",
    spread: "6px",
    color: "0 0 0",
    opacity: 12,
    inset: false,
  },
  {
    id: "51",
    offsetX: "4px",
    offsetY: "32px",
    blur: "86px",
    spread: "24px",
    color: "0 0 0",
    opacity: 7,
    inset: false,
  },
  {
    id: "52",
    offsetX: "32px",
    offsetY: "68px",
    blur: "68px",
    spread: "40px",
    color: "0 0 0",
    opacity: 5,
    inset: false,
  },
  {
    id: "53",
    offsetX: 0,
    offsetY: "32px",
    blur: "48px",
    spread: "24px",
    color: "0 0 0",
    opacity: 7,
    inset: false,
  },
  {
    id: "54",
    offsetX: "-42px",
    offsetY: "52px",
    blur: "68px",
    spread: "4px",
    color: "0 0 0",
    opacity: 6,
    inset: false,
  },
  {
    id: "55",
    offsetX: "42px",
    offsetY: "52px",
    blur: "68px",
    spread: "4px",
    color: "0 0 0",
    opacity: 6,
    inset: false,
  },
  {
    id: "56",
    offsetX: "-96px",
    offsetY: "96px",
    blur: "86px",
    spread: "24px",
    color: "0 0 0",
    opacity: 7,
    inset: false,
  },
  {
    id: "57",
    offsetX: "96px",
    offsetY: "96px",
    blur: "86px",
    spread: "24px",
    color: "0 0 0",
    opacity: 7,
    inset: false,
  },
  {
    id: "58",
    offsetX: 0,
    offsetY: 0,
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 0,
    inset: false,
  },
  {
    id: "59",
    offsetX: 0,
    offsetY: 0,
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 0,
    inset: false,
  },
  {
    id: "60",
    offsetX: 0,
    offsetY: 0,
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 0,
    inset: false,
  },
  {
    id: "61",
    offsetX: 0,
    offsetY: 0,
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 0,
    inset: false,
  },
  {
    id: "62",
    offsetX: 0,
    offsetY: 0,
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 0,
    inset: false,
  },
  {
    id: "63",
    offsetX: 0,
    offsetY: 0,
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 0,
    inset: false,
  },
  {
    id: "64",
    offsetX: 0,
    offsetY: 0,
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 0,
    inset: false,
    /* },
  {
    id: "",
    offsetX: 0,
    offsetY: 0,
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 0,
    inset: false, */
  },
];
