export const base = {
  id: "-1",
    name: "",
  inset: false,
  offsetX: 0,
  offsetY: "2px",
  blur: "8px",
  spread: 0,
  color: "50 50 50",
  opacity: 8,
};

export const collection = [
  {
    id: "0",
    name: "",
    inset: false,
    offsetX: 0,
    offsetY: 0,
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 0,
  },
  {
    id: "1",
    name: "",
    inset: false,
    offsetX: 0,
    offsetY: 0,
    blur: "20px",
    spread: 0,
    color: "150 150 150",
    opacity: 10,
  },
  {
    id: "2",
    name: "",
    inset: false,
    offsetX: 0,
    offsetY: "20px",
    blur: "60px",
    spread: "-10px",
    color: "0 0 0",
    opacity: 10,
  },
  {
    id: "3",
    name: "",
    inset: false,
    offsetX: 0,
    offsetY: "6px",
    blur: "9px",
    spread: 0,
    color: "0 0 0",
    opacity: 9,
  },
  {
    id: "4",
    name: "",
    inset: false,
    offsetX: 0,
    offsetY: "5px",
    blur: "20px",
    spread: 0,
    color: "0 0 0",
    opacity: 10,
  },
  {
    id: "5",
    name: "",
    inset: false,
    offsetX: 0,
    offsetY: "3px",
    blur: "13px",
    spread: "1px",
    color: "0 0 0",
    opacity: 12,
  },
  {
    id: "6",
    name: "",
    multiple: [
      {
        inset: false,
        offsetX: 0,
        offsetY: "15px",
        blur: "35px",
        spread: 0,
        color: "0 0 0",
        opacity: 10,
      },
      {
        inset: false,
        offsetX: 0,
        offsetY: "3px",
        blur: "10px",
        spread: 0,
        color: "0 0 0",
        opacity: 7,
      },
    ],
  },
  {
    id: "7",
    name: "",
    multiple: [
      {
        inset: false,
        offsetX: 0,
        offsetY: 0,
        blur: "1px",
        spread: 0,
        color: "57 70 78",
        opacity: 15,
      },
      {
        inset: false,
        offsetX: 0,
        offsetY: "20px",
        blur: "55px",
        spread: "-8px",
        color: "57 70 78",
        opacity: 25,
      },
    ],
  },
  {
    id: "8",
    name: "",
    inset: false,
    offsetX: 0,
    offsetY: "15px",
    blur: "45px",
    spread: "-9px",
    color: "0 0 0",
    opacity: 25,
  },
  {
    id: "9",
    name: "",
    inset: false,
    offsetX: "1px",
    offsetY: "1px",
    blur: "1px",
    spread: 0,
    color: "0 0 0",
    opacity: 6,
  },
  {
    id: "10",
    name: "",
    inset: false,
    offsetX: 0,
    offsetY: "2px",
    blur: "6px",
    spread: 0,
    color: "0 0 0",
    opacity: 40,
  },
  {
    id: "11",
    name: "",
    inset: false,
    offsetX: 0,
    offsetY: "6px",
    blur: "16px",
    spread: 0,
    color: "0 0 0",
    opacity: 30,
  },
  {
    id: "12",
    name: "",
    multiple: [
      {
        inset: false,
        offsetX: 0,
        offsetY: "16px",
        blur: "38px",
        spread: "-12px",
        color: "62 57 107",
        opacity: 36,
      },
      {
        inset: false,
        offsetX: 0,
        offsetY: "4px",
        blur: "25px",
        spread: 0,
        color: "62 57 107",
        opacity: 12,
      },
      {
        inset: false,
        offsetX: 0,
        offsetY: "8px",
        blur: "10px",
        spread: "-5px",
        color: "62 57 107",
        opacity: 20,
      },
    ],
  },
  {
    id: "13",
    name: "",
    inset: false,
    offsetX: 0,
    offsetY: "-15px",
    blur: "5px",
    spread: "-12px",
    color: "0 0 0",
    opacity: 20,
  },
  {
    id: "14",
    name: "",
    inset: false,
    offsetX: 0,
    offsetY: "-6px",
    blur: "9px",
    spread: 0,
    color: "0 0 0",
    opacity: 9,
  },
  {
    id: "15",
    name: "",
    inset: false,
    offsetX: 0,
    offsetY: "-20px",
    blur: "60px",
    spread: "-10px",
    color: "0 0 0",
    opacity: 10,
  },
  {
    id: "16",
    name: "",
    inset: false,
    offsetX: 0,
    offsetY: "-50px",
    blur: "100px",
    spread: "-30px",
    color: "16 36 94",
    opacity: 25,
  },
  {
    id: "17",
    name: "",
    inset: false,
    offsetX: 0,
    offsetY: "-16px",
    blur: "24px",
    spread: 0,
    color: "112 128 175",
    opacity: 20,
  },
  {
    id: "18",
    name: "",
    multiple: [
      {
        offsetX: 0,
        offsetY: "16px",
        blur: "32px",
        spread: 0,
        color: "72 76 89",
        opacity: 28,
      },
      {
        offsetX: 0,
        offsetY: 0,
        inset: false,
        blur: 0,
        spread: 0,
        color: "transparent",
        opacity: 0,
      },
    ],
  },
  {
    id: "19",
    name: "",
    multiple: [
      {
        offsetX: 0,
        offsetY: "-16px",
        blur: "32px",
        spread: 0,
        color: "72 76 89",
        opacity: 28,
      },
      {
        offsetX: 0,
        offsetY: 0,
        blur: 0,
        spread: 0,
        color: "transparent",
        opacity: 0,
      },
    ],
  },
  {
    id: "20",
    name: "",
    inset: false,
    offsetX: 0,
    offsetY: "-30px",
    blur: "40px",
    spread: 0,
    color: "16 36 94",
    opacity: 20,
  },
  {
    id: "21",
    name: "",
    inset: false,
    offsetX: "5px",
    offsetY: "5px",
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 5,
  },
  {
    id: "22",
    name: "",
    inset: false,
    offsetX: "-5px",
    offsetY: "5px",
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 5,
  },
  {
    id: "23",
    name: "",
    inset: false,
    offsetX: "5px",
    offsetY: "-5px",
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 5,
  },
  {
    id: "24",
    name: "",
    inset: false,
    offsetX: "-5px",
    offsetY: "-5px",
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 5,
  },
  {
    id: "25",
    name: "",
    inset: false,
    offsetX: "2px",
    offsetY: "2px",
    blur: "4px",
    spread: 0,
    color: "72 76 89",
    opacity: 20,
  },
  {
    id: "26",
    name: "",
    inset: false,
    offsetX: "-2px",
    offsetY: "2px",
    blur: "4px",
    spread: 0,
    color: "72 76 89",
    opacity: 20,
  },
  {
    id: "27",
    name: "",
    inset: false,
    offsetX: "2px",
    offsetY: "-2px",
    blur: "4px",
    spread: 0,
    color: "72 76 89",
    opacity: 20,
  },
  {
    id: "28",
    name: "",
    inset: false,
    offsetX: "-2px",
    offsetY: "-2px",
    blur: "4px",
    spread: 0,
    color: "72 76 89",
    opacity: 20,
  },
  {
    id: "29",
    name: "",
    inset: false,
    offsetX: "2px",
    offsetY: "4px",
    blur: "6px",
    spread: "1px",
    color: "160 167 186",
    opacity: 14,
  },
  {
    id: "30",
    name: "",
    inset: false,
    offsetX: "-2px",
    offsetY: "4px",
    blur: "6px",
    spread: "1px",
    color: "160 167 186",
    opacity: 14,
  },
  {
    id: "31",
    name: "",
    inset: false,
    offsetX: "2px",
    offsetY: "-4px",
    blur: "6px",
    spread: "1px",
    color: "160 167 186",
    opacity: 14,
  },
  {
    id: "32",
    name: "",
    inset: false,
    offsetX: "-2px",
    offsetY: "-4px",
    blur: "6px",
    spread: "1px",
    color: "160 167 186",
    opacity: 14,
  },
  {
    id: "33",
    name: "",
    inset: false,
    offsetX: "15px",
    offsetY: "15px",
    blur: "5px",
    spread: "-5px",
    color: "0 0 0",
    opacity: 20,
  },
  {
    id: "34",
    name: "",
    inset: false,
    offsetX: "-15px",
    offsetY: "15px",
    blur: "5px",
    spread: "-5px",
    color: "0 0 0",
    opacity: 20,
  },
  {
    id: "35",
    name: "",
    inset: false,
    offsetX: "15px",
    offsetY: "-15px",
    blur: "5px",
    spread: "-5px",
    color: "0 0 0",
    opacity: 20,
  },
  {
    id: "36",
    name: "",
    inset: false,
    offsetX: "-15px",
    offsetY: "-15px",
    blur: "5px",
    spread: "-5px",
    color: "0 0 0",
    opacity: 20,
  },
  {
    id: "37",
    name: "",
    multiple: [
      {
        inset: false,
        offsetX: "10px",
        offsetY: "10px",
        blur: "32px",
        spread: 0,
        color: "62 57 107",
        opacity: 28,
      },
      {
        offsetX: 0,
        offsetY: 0,
        blur: 0,
        spread: 0,
        color: "transparent",
        opacity: 0,
      },
    ],
  },
  {
    id: "38",
    name: "",
    multiple: [
      {
        inset: false,
        offsetX: "-10px",
        offsetY: "10px",
        blur: "32px",
        spread: 0,
        color: "62 57 107",
        opacity: 28,
      },
      {
        offsetX: 0,
        offsetY: 0,
        blur: 0,
        spread: 0,
        color: "transparent",
        opacity: 0,
      },
    ],
  },
  {
    id: "39",
    name: "",
    multiple: [
      {
        inset: false,
        offsetX: "10px",
        offsetY: "-10px",
        blur: "32px",
        spread: 0,
        color: "62 57 107",
        opacity: 28,
      },
      {
        offsetX: 0,
        offsetY: 0,
        blur: 0,
        spread: 0,
        color: "transparent",
        opacity: 0,
      },
    ],
  },
  {
    id: "40",
    name: "",
    multiple: [
      {
        inset: false,
        offsetX: "-10px",
        offsetY: "-10px",
        blur: "32px",
        spread: 0,
        color: "62 57 107",
        opacity: 28,
      },
      {
        offsetX: 0,
        offsetY: 0,
        blur: 0,
        spread: 0,
        color: "transparent",
        opacity: 0,
      },
    ],
  },
  {
    id: "41",
    name: "",
    multiple: [
      {
        inset: false,
        offsetX: "1px",
        offsetY: "1px",
        blur: "5px",
        spread: 0,
        color: "26 26 67",
        opacity: 5,
      },
      {
        inset: false,
        offsetX: "39px",
        offsetY: "63px",
        blur: "125px",
        spread: "-25px",
        color: "50 50 93",
        opacity: 50,
      },
      {
        inset: false,
        offsetX: "24px",
        offsetY: "38px",
        blur: "75px",
        spread: "-38px",
        color: "0 0 0",
        opacity: 30,
      },
    ],
  },
  {
    id: "42",
    name: "",
    multiple: [
      {
        inset: false,
        offsetX: "1px",
        offsetY: "1px",
        blur: "5px",
        spread: 0,
        color: "26 26 67",
        opacity: 5,
      },
      {
        inset: false,
        offsetX: "-39px",
        offsetY: "63px",
        blur: "125px",
        spread: "-25px",
        color: "50 50 93",
        opacity: 50,
      },
      {
        inset: false,
        offsetX: "24px",
        offsetY: "38px",
        blur: "75px",
        spread: "-38px",
        color: "0 0 0",
        opacity: 30,
      },
    ],
  },
  {
    id: "43",
    name: "",
    inset: false,
    offsetX: 0,
    offsetY: "15px",
    blur: "5px",
    spread: "-12px",
    color: "0 0 0",
    opacity: 20,
  },
  {
    id: "44",
    name: "",
    inset: false,
    offsetX: 0,
    offsetY: "50px",
    blur: "100px",
    spread: "-30px",
    color: "16 36 94",
    opacity: 25,
  },
  {
    id: "45",
    name: "",
    inset: false,
    offsetX: 0,
    offsetY: "8px",
    blur: "16px",
    spread: 0,
    color: "0 0 0",
    opacity: 5,
  },
  {
    id: "46",
    name: "",
    inset: false,
    offsetX: 0,
    offsetY: "6px",
    blur: "9px",
    spread: 0,
    color: "0 0 0",
    opacity: 9,
  },
  {
    id: "47",
    name: "",
    inset: false,
    offsetX: 0,
    offsetY: "16px",
    blur: "24px",
    spread: 0,
    color: "112 128 175",
    opacity: 20,
  },
  {
    id: "48",
    name: "",
    multiple: [
      {
        inset: false,
        offsetX: 0,
        offsetY: "16px",
        blur: "32px",
        spread: 0,
        color: "72 76 89",
        opacity: 28,
      },
      {
        offsetX: 0,
        offsetY: 0,
        blur: 0,
        spread: 0,
        color: "transparent",
        opacity: 0,
      },
    ],
  },
  {
    id: "49",
    name: "",
    inset: false,
    offsetX: 0,
    offsetY: "30px",
    blur: "40px",
    spread: 0,
    color: "16 36 94",
    opacity: 20,
  },
  {
    id: "50",
    name: "",
    inset: false,
    offsetX: 0,
    offsetY: 0,
    blur: "70px",
    spread: "6px",
    color: "0 0 0",
    opacity: 12,
  },
  {
    id: "51",
    name: "",
    inset: false,
    offsetX: "5px",
    offsetY: "31px",
    blur: "85px",
    spread: "23px",
    color: "0 0 0",
    opacity: 7,
  },
  {
    id: "52",
    name: "",
    inset: false,
    offsetX: "30px",
    offsetY: "70px",
    blur: "70px",
    spread: "40px",
    color: "0 0 0",
    opacity: 5,
  },
  {
    id: "53",
    name: "",
    inset: false,
    offsetX: 0,
    offsetY: "30px",
    blur: "48px",
    spread: "22px",
    color: "0 0 0",
    opacity: 7,
  },
  {
    id: "54",
    name: "",
    inset: false,
    offsetX: "-41px",
    offsetY: "51px",
    blur: "68px",
    spread: "5px",
    color: "0 0 0",
    opacity: 6,
  },
  {
    id: "55",
    name: "",
    inset: false,
    offsetX: "41px",
    offsetY: "51px",
    blur: "68px",
    spread: "5px",
    color: "0 0 0",
    opacity: 6,
  },
  {
    id: "56",
    name: "",
    inset: false,
    offsetX: "-100px",
    offsetY: "100px",
    blur: "85px",
    spread: "23px",
    color: "0 0 0",
    opacity: 7,
  },
  {
    id: "57",
    name: "",
    inset: false,
    offsetX: "100px",
    offsetY: "100px",
    blur: "85px",
    spread: "23px",
    color: "0 0 0",
    opacity: 7,
  },
  {
    id: "58",
    name: "",
    multiple: [
      {
        inset: false,
        offsetX: "5px",
        offsetY: 0,
        blur: "12px",
        spread: "-10px",
        color: "0 0 0",
        opacity: 25,
      },
      {
        offsetX: "-5px",
        offsetY: 0,
        blur: "12px",
        spread: "-10px",
        color: "0 0 0",
        opacity: 25,
      },
    ],
  },
  {
    id: "59",
    name: "",
    multiple: [
      {
        offsetX: "6px",
        offsetY: 0,
        blur: "12px",
        spread: "-8px",
        color: "160 167 186",
        opacity: 45,
      },
      {
        offsetX: "-6px",
        offsetY: 0,
        blur: "12px",
        spread: "-8px",
        color: "160 167 186",
        opacity: 45,
      },
    ],
  },
  {
    id: "60",
    name: "",
    multiple: [
      {
        offsetX: "6px",
        offsetY: 0,
        blur: "12px",
        spread: "-7px",
        color: "160 167 186",
        opacity: 75,
      },
      {
        offsetX: "-6px",
        offsetY: 0,
        blur: "12px",
        spread: "-7px",
        color: "160 167 186",
        opacity: 75,
      },
    ],
  },
  {
    id: "61",
    name: "",
    multiple: [
      {
        offsetX: "-20px",
        offsetY: 0,
        blur: "50px",
        spread: "-25px",
        color: "160 167 186",
        opacity: 65,
      },
      {
        offsetX: "20px",
        offsetY: 0,
        blur: "50px",
        spread: "-25px",
        color: "160 167 186",
        opacity: 65,
      },
    ],
  },
  {
    id: "62",
    name: "",
    multiple: [
      {
        offsetX: "20px",
        offsetY: 0,
        blur: "25px",
        spread: "-15px",
        color: "160 167 186",
        opacity: 35,
      },
      {
        offsetX: "-20px",
        offsetY: 0,
        blur: "25px",
        spread: "-15px",
        color: "160 167 186",
        opacity: 35,
      },
    ],
  },
  {
    id: "63",
    name: "",
    multiple: [
      {
        offsetX: 0,
        offsetY: "11px",
        blur: "30px",
        spread: "-20px",
        color: "160 167 186",
        opacity: 51,
      },
      {
        offsetX: 0,
        offsetY: "-12px",
        blur: "30px",
        spread: "-20px",
        color: "160 167 186",
        opacity: 51,
      },
    ],
  },
  {
    id: "64",
    name: "",
    multiple: [
      {
        offsetX: 0,
        offsetY: "11px",
        blur: "8px",
        spread: "-10px",
        color: "160 167 186",
        opacity: 51,
      },
      {
        offsetX: 0,
        offsetY: "-11px",
        blur: "8px",
        spread: "-10px",
        color: "160 167 186",
        opacity: 51,
      },
    ],
  },
];
