export const baseShadow = {
  id: "-1",
  offsetX: "0",
  offsetY: "0.125rem",
  blur: "0.5rem",
  spread: "0",
  color: "0 0 0",
  opacity: 8,
  inset: false,
};

export const listShadows = [
  {
    id: "0",
    offsetX: 0,
    offsetY: 0,
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 0,
    inset: false,
  },
  {
    id: "1",
    offsetX: 0,
    offsetY: 0,
    blur: "1.25rem",
    spread: 0,
    color: "0 0 0",
    opacity: 10,
    inset: false,
  },
  {
    id: "2",
    offsetX: 0,
    offsetY: "1.25rem",
    blur: "3.75rem",
    spread: "-0.625rem",
    color: "0 0 0",
    opacity: 10,
    inset: false,
  },
  {
    id: "3",
    offsetX: 0,
    offsetY: "0.375rem",
    blur: "0.5rem",
    spread: "0",
    color: "0 0 0",
    opacity: 10,
    inset: false,
  },
  {
    id: "4",
    offsetX: 0,
    offsetY: "0.375rem",
    blur: "1.25rem",
    spread: 0,
    color: "0 0 0",
    opacity: 10,
    inset: false,
  },
  {
    id: "5",
    offsetX: "0",
    offsetY: "0.25rem",
    blur: "0.75rem",
    spread: "0.125rem",
    color: "0 0 0",
    opacity: 12,
    inset: false,
  },
  {
    id: "6",
    multiple: [
      {
        offsetX: 0,
        offsetY: "1rem",
        blur: "2rem",
        spread: 0,
        color: "0 0 0",
        opacity: 10,
        inset: false,
      },
      {
        offsetX: 0,
        offsetY: "0.25rem",
        blur: "0.75rem",
        spread: 0,
        color: "0 0 0",
        opacity: 7,
        inset: false,
      },
    ],
  },
  {
    id: "7",
    multiple: [
      {
        offsetX: 0,
        offsetY: 0,
        blur: "0.125rem",
        spread: 0,
        color: "0 0 0",
        opacity: 15,
        inset: false,
      },
      {
        offsetX: 0,
        offsetY: "1.25rem",
        blur: "3.5rem",
        spread: "-0.5rem",
        color: "0 0 0",
        opacity: 25,
        inset: false,
      },
    ],
  },
  {
    id: "8",
    offsetX: 0,
    offsetY: "1rem",
    blur: "2.75rem",
    spread: "-0.75rem",
    color: "0 0 0",
    opacity: 25,
    inset: false,
  },
  {
    id: "9",
    offsetX: "0.125rem",
    offsetY: "0.125rem",
    blur: "0.125rem",
    spread: 0,
    color: "0 0 0",
    opacity: 6,
    inset: false,
  },
  {
    id: "10",
    offsetX: 0,
    offsetY: "0.125rem",
    blur: "0.375rem",
    spread: 0,
    color: "0 0 0",
    opacity: 40,
    inset: false,
  },
  {
    id: "11",
    offsetX: 0,
    offsetY: "0.375rem",
    blur: "1rem",
    spread: 0,
    color: "0 0 0",
    opacity: 30,
    inset: false,
  },
  {
    id: "12",
    multiple: [
      {
        offsetX: 0,
        offsetY: "1rem",
        blur: "2.375rem",
        spread: "-0.75rem",
        color: "0 0 0",
        opacity: 36,
        inset: false,
      },
      {
        offsetX: 0,
        offsetY: ".25rem",
        blur: "1.5625rem",
        spread: 0,
        color: "0 0 0",
        opacity: 12,
        inset: false,
      },
      {
        offsetX: 0,
        offsetY: ".5rem",
        blur: ".625rem",
        spread: "-0.375rem",
        color: "0 0 0",
        opacity: 20,
        inset: false,
      },
    ],
  },
  {
    id: "13",
    offsetX: 0,
    offsetY: "-1rem",
    blur: "0.375rem",
    spread: "-0.75rem",
    color: "0 0 0",
    opacity: 20,
    inset: false,
  },
  {
    id: "14",
    offsetX: 0,
    offsetY: "-0.375rem",
    blur: "0.5rem",
    spread: 0,
    color: "0 0 0",
    opacity: 10,
    inset: false,
  },
  {
    id: "15",
    offsetX: 0,
    offsetY: "-1.25rem",
    blur: "3.75rem",
    spread: "-0.75rem",
    color: "0 0 0",
    opacity: 10,
    inset: false,
  },
  {
    id: "16",
    offsetX: 0,
    offsetY: "-3.125rem",
    blur: "6.25rem",
    spread: "-1.875rem",
    color: "0 0 0",
    opacity: 25,
    inset: false,
  },
  {
    id: "17",
    offsetX: 0,
    offsetY: "-1rem",
    blur: "1.5rem",
    spread: 0,
    color: "0 0 0",
    opacity: 20,
    inset: false,
  },
  {
    id: "18",
    multiple: [
      {
        offsetX: 0,
        offsetY: "-1rem",
        blur: "2rem",
        spread: 0,
        color: "0 0 0",
        opacity: 28,
      },
      {
        offsetX: 0,
        offsetY: 0,
        blur: 0,
        spread: 0,
        color: "transparent",
        opacity: 0,
      },
    ],
    inset: false,
  },
  {
    id: "19",
    multiple: [
      {
        offsetX: 0,
        offsetY: "1rem",
        blur: "2rem",
        spread: 0,
        color: "0 0 0",
        opacity: 28,
      },
      {
        offsetX: 0,
        offsetY: 0,
        blur: 0,
        spread: 0,
        color: "transparent",
        opacity: 0,
      },
    ],
  },
  {
    id: "20",
    offsetX: 0,
    offsetY: "-2rem",
    blur: "2.5rem",
    spread: 0,
    color: "0 0 0",
    opacity: 20,
    inset: false,
  },
  {
    id: "21",
    offsetX: "0.375rem",
    offsetY: "0.375rem",
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 5,
    inset: false,
  },
  {
    id: "22",
    offsetX: "-0.375rem",
    offsetY: "0.375rem",
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 5,
    inset: false,
  },
  {
    id: "23",
    offsetX: "0.375rem",
    offsetY: "-0.375rem",
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 0,
    inset: false,
  },
  {
    id: "24",
    offsetX: "-0.375rem",
    offsetY: "-0.375rem",
    blur: 0,
    spread: 0,
    color: "0 0 0",
    opacity: 0,
    inset: false,
  },
  {
    id: "25",
    offsetX: "0.125rem",
    offsetY: "0.125rem",
    blur: "0.25rem",
    spread: 0,
    color: "0 0 0",
    opacity: 20,
    inset: false,
  },
  {
    id: "26",
    offsetX: "-0.125rem",
    offsetY: "0.125rem",
    blur: "0.25rem",
    spread: 0,
    color: "0 0 0",
    opacity: 20,
    inset: false,
  },
  {
    id: "27",
    offsetX: "0.125rem",
    offsetY: "-0.125rem",
    blur: "0.25rem",
    spread: 0,
    color: "0 0 0",
    opacity: 20,
    inset: false,
  },
  {
    id: "28",
    offsetX: "-0.125rem",
    offsetY: "-0.125rem",
    blur: "0.25rem",
    spread: 0,
    color: "0 0 0",
    opacity: 20,
    inset: false,
  },
  {
    id: "29",
    offsetX: "0.125rem",
    offsetY: "0.25rem",
    blur: "0.375rem",
    spread: 0,
    color: "0 0 0",
    opacity: 14,
    inset: false,
  },
  {
    id: "30",
    offsetX: "-0.125rem",
    offsetY: "0.25rem",
    blur: "0.375rem",
    spread: 0,
    color: "0 0 0",
    opacity: 14,
    inset: false,
  },
  {
    id: "31",
    offsetX: "0.125rem",
    offsetY: "-0.25rem",
    blur: "0.375rem",
    spread: 0,
    color: "0 0 0",
    opacity: 14,
    inset: false,
  },
  {
    id: "32",
    offsetX: "-0.125rem",
    offsetY: "-0.25rem",
    blur: "0.375rem",
    spread: 0,
    color: "0 0 0",
    opacity: 14,
    inset: false,
  },
  {
    id: "33",
    offsetX: "1rem",
    offsetY: "1rem",
    blur: "0.25rem",
    spread: "-0.25rem",
    color: "0 0 0",
    opacity: 20,
    inset: false,
  },
  {
    id: "34",
    offsetX: "-1rem",
    offsetY: "1rem",
    blur: "0.25rem",
    spread: "-0.25rem",
    color: "0 0 0",
    opacity: 20,
    inset: false,
  },
  {
    id: "35",
    offsetX: "1rem",
    offsetY: "-1rem",
    blur: "0.25rem",
    spread: "-0.25rem",
    color: "0 0 0",
    opacity: 20,
    inset: false,
  },
  {
    id: "36",
    offsetX: "-1rem",
    offsetY: "-1rem",
    blur: "0.25rem",
    spread: "-0.25rem",
    color: "0 0 0",
    opacity: 20,
    inset: false,
  },
  {
    id: "37",
    multiple: [
      {
        offsetX: "0.75rem",
        offsetY: "0.75rem",
        blur: "2rem",
        spread: 0,
        color: "0 0 0",
        opacity: 28,
        inset: false,
      },
      {
        offsetX: 0,
        offsetY: 0,
        blur: 0,
        spread: 0,
        color: "transparent",
        opacity: 0,
      },
    ],
  },
  {
    id: "38",
    multiple: [
      {
        offsetX: "-0.75rem",
        offsetY: "0.75rem",
        blur: "2rem",
        spread: 0,
        color: "0 0 0",
        opacity: 28,
        inset: false,
      },
      {
        offsetX: 0,
        offsetY: 0,
        blur: 0,
        spread: 0,
        color: "transparent",
        opacity: 0,
      },
    ],
  },
  {
    id: "39",
    multiple: [
      {
        offsetX: "0.75rem",
        offsetY: "-0.75rem",
        blur: "2rem",
        spread: 0,
        color: "0 0 0",
        opacity: 28,
        inset: false,
      },
      {
        offsetX: 0,
        offsetY: 0,
        blur: 0,
        spread: 0,
        color: "transparent",
        opacity: 0,
      },
    ],
  },
  {
    id: "40",
    multiple: [
      {
        offsetX: "-0.75rem",
        offsetY: "-0.75rem",
        blur: "2rem",
        spread: 0,
        color: "0 0 0",
        opacity: 28,
        inset: false,
      },
      {
        offsetX: 0,
        offsetY: 0,
        blur: 0,
        spread: 0,
        color: "transparent",
        opacity: 0,
      },
    ],
  },
  {
    id: "41",
    multiple: [
      {
        offsetX: "0.125rem",
        offsetY: "0.125rem",
        blur: "0.375rem",
        spread: 0,
        color: "0 0 0",
        opacity: 5,
        inset: false,
      },
      {
        offsetX: "2.375rem",
        offsetY: "3.875rem",
        blur: "7.875rem",
        spread: "-1.5rem",
        color: "0 0 0",
        opacity: 50,
        inset: false,
      },
      {
        offsetX: "1.5rem",
        offsetY: "2.375rem",
        blur: "4.75rem",
        spread: "-2.25rem",
        color: "0 0 0",
        opacity: 30,
        inset: false,
      },
    ],
  },
  {
    id: "42",
    multiple: [
      {
        offsetX: "0.125rem",
        offsetY: "0.125rem",
        blur: "0.375rem",
        spread: 0,
        color: "0 0 0",
        opacity: 5,
        inset: false,
      },
      {
        offsetX: "-2.375rem",
        offsetY: "3.875rem",
        blur: "7.875rem",
        spread: "-1.5rem",
        color: "0 0 0",
        opacity: 50,
        inset: false,
      },
      {
        offsetX: "1.5rem",
        offsetY: "2.375rem",
        blur: "4.75rem",
        spread: "-2.25rem",
        color: "0 0 0",
        opacity: 30,
        inset: false,
      },
    ],
  },
  {
    id: "43",
    offsetX: 0,
    offsetY: "1rem",
    blur: "0.25rem",
    spread: "-0.75rem",
    color: "0 0 0",
    opacity: 20,
    inset: false,
  },
  {
    id: "44",
    offsetX: 0,
    offsetY: "3rem",
    blur: "6rem",
    spread: "-2rem",
    color: "0 0 0",
    opacity: 25,
    inset: false,
  },
  {
    id: "45",
    offsetX: 0,
    offsetY: "0.5rem",
    blur: "1rem",
    spread: 0,
    color: "0 0 0",
    opacity: 5,
    inset: false,
  },
  {
    id: "46",
    offsetX: 0,
    offsetY: "0.375rem",
    blur: "0.5rem",
    spread: 0,
    color: "0 0 0",
    opacity: 10,
    inset: false,
  },
  {
    id: "47",
    offsetX: 0,
    offsetY: "1rem",
    blur: "1.5rem",
    spread: 0,
    color: "0 0 0",
    opacity: 20,
    inset: false,
  },
  {
    id: "48",
    multiple: [
      {
        offsetX: 0,
        offsetY: "1rem",
        blur: "2rem",
        spread: 0,
        color: "0 0 0",
        opacity: 28,
        inset: false,
      },
      {
        offsetX: 0,
        offsetY: 0,
        blur: 0,
        spread: 0,
        color: "transparent",
        opacity: 0,
      },
    ],
  },
  {
    id: "49",
    offsetX: 0,
    offsetY: "2rem",
    blur: "2.5rem",
    spread: 0,
    color: "0 0 0",
    opacity: 20,
    inset: false,
  },
  {
    id: "50",
    offsetX: 0,
    offsetY: 0,
    blur: "4.25rem",
    spread: "0.375rem",
    color: "0 0 0",
    opacity: 12,
    inset: false,
  },
  {
    id: "51",
    offsetX: "0.25rem",
    offsetY: "2rem",
    blur: "5.375rem",
    spread: "1.5rem",
    color: "0 0 0",
    opacity: 7,
    inset: false,
  },
  {
    id: "52",
    offsetX: "2rem",
    offsetY: "4.25rem",
    blur: "4.25rem",
    spread: "2.5rem",
    color: "0 0 0",
    opacity: 5,
    inset: false,
  },
  {
    id: "53",
    offsetX: 0,
    offsetY: "2rem",
    blur: "3rem",
    spread: "1.5rem",
    color: "0 0 0",
    opacity: 7,
    inset: false,
  },
  {
    id: "54",
    offsetX: "-2.625rem",
    offsetY: "3.25rem",
    blur: "4.25rem",
    spread: "0.25rem",
    color: "0 0 0",
    opacity: 6,
    inset: false,
  },
  {
    id: "55",
    offsetX: "2.625rem",
    offsetY: "3.25rem",
    blur: "4.25rem",
    spread: "0.25rem",
    color: "0 0 0",
    opacity: 6,
    inset: false,
  },
  {
    id: "56",
    offsetX: "-6rem",
    offsetY: "6rem",
    blur: "5.375rem",
    spread: "1.5rem",
    color: "0 0 0",
    opacity: 7,
    inset: false,
  },
  {
    id: "57",
    offsetX: "6rem",
    offsetY: "6rem",
    blur: "5.375rem",
    spread: "1.5rem",
    color: "0 0 0",
    opacity: 7,
    inset: false,
  },
  {
    id: "58",
    multiple: [
      {
        offsetX: "0.375rem",
        offsetY: 0,
        blur: "0.75rem",
        spread: "0.625rem",
        color: "0 0 0",
        opacity: 25,
        inset: false,
      },
      {
        offsetX: "-0.375rem",
        offsetY: 0,
        blur: "0.75rem",
        spread: "0.625rem",
        color: "0 0 0",
        opacity: 25,
      },
    ],
  },
  {
    id: "59",
    multiple: [
      {
        offsetX: "0.375rem",
        offsetY: 0,
        blur: "0.75rem",
        spread: "-0.5rem",
        color: "0 0 0",
        opacity: 45,
      },
      {
        offsetX: "-0.375rem",
        offsetY: 0,
        blur: "0.75rem",
        spread: "0.5rem",
        color: "0 0 0",
        opacity: 45,
      },
    ],
  },
  {
    id: "60",
    multiple: [
      {
        offsetX: "6px",
        offsetY: 0,
        blur: "12px",
        spread: "-8px",
        color: "0 0 0",
        opacity: 75,
      },
      {
        offsetX: "-6px",
        offsetY: 0,
        blur: "12px",
        spread: "-8px",
        color: "0 0 0",
        opacity: 75,
      },
    ],
  },
  {
    id: "61",
    multiple: [
      {
        offsetX: "-20px",
        offsetY: 0,
        blur: "48px",
        spread: "-24px",
        color: "0 0 0",
        opacity: 65,
      },
      {
        offsetX: "20px ",
        offsetY: 0,
        blur: "48px",
        spread: "-24px",
        color: "0 0 0",
        opacity: 65,
      },
    ],
  },
  {
    id: "62",
    multiple: [
      {
        offsetX: "20px",
        offsetY: 0,
        blur: "24px",
        spread: "-16px",
        color: "0 0 0",
        opacity: 35,
      },
      {
        offsetX: "-20px",
        offsetY: 0,
        blur: "24px",
        spread: "-16px",
        color: "0 0 0",
        opacity: 35,
      },
    ],
  },
  {
    id: "63",
    multiple: [
      {
        offsetX: 0,
        offsetY: "12px",
        blur: "32px",
        spread: "-20px",
        color: "0 0 0",
        opacity: 51,
      },
      {
        offsetX: 0,
        offsetY: "-12px",
        blur: "32px",
        spread: "-20px",
        color: "0 0 0",
        opacity: 51,
      },
    ],
  },
  {
    id: "64",
    multiple: [
      {
        offsetX: 0,
        offsetY: "12px",
        blur: "8px",
        spread: "-10px",
        color: "0 0 0",
        opacity: 51,
      },
      {
        offsetX: 0,
        offsetY: "-12px",
        blur: "8px",
        spread: "-10px",
        color: "0 0 0",
        opacity: 51,
      },
    ],
  },
];
